### ISSUE TITLE
Link header for server push

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#101]
It would be nice if you could set link headers for pushing assets to the user. Especially the [HTTP/2 server push](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) is an efficient way of doing that and it really speeds up website loadings.

And you have a lot of assets, which are *always* loaded, so this is a very good scenario for HTTP/2 server push.

You can also [use it with PHP](https://blog.cloudflare.com/using-http-2-server-push-with-php/).
However I know that only static files are loaded when the site is first requested. Therefore you may only be able to use this problem in the webserver config. Basically you need to add some `Link` headers sent when `/index.html` is requested.
For this a configuration example/list of headers to send would be useful. This is especially difficult as there are files such as `/assets/vendor-7ba53f36a20a09883cc55681a02c8a12.js`, which really seem to have much randomness in its filename. :wink: 
So it would maybe useful to integrate this into the build script.

**Comment by jelhan** [comment]
I'm not quite sure if croodle would profit much from server push.

In current master it's only 5 assets: croodle.js, croodle.css, vendor.js, vendor.css and glyphicons-halflings-regular.*. Except for font they are all included at top of index.html which is less than 3 KB. Not taking network performance into account (localhost) I measured a latency of 50 ms in Chromium (~160 ms for Firefox). Fonts shouldn't be pushed since we don't know which format is supported by browser/OS. So it's just about 4 extra round trips.

I think pushing api calls would really speedup croodle cause they are not requested until croodle.js and vendor.js are loaded and processed. But that's not possible in current implementation since croodle uses anchor-based URLs and therefore server doesn't know which poll is requested.

Having that said I'm even not sure how to help with it. Of course we could generate necessary Link headers depending on current asset fingerprints on build but ho to implement in a deployment strategy? If we are talking about performance a .htaccess file should not be used cause it's parsed on every requested. So a deployment strategy must update virtual site config. I guess taking responsibilty for calculating Link headers wouldn't make any difference in such a complex setup or?

Also you could decide to disable fingerprinting assets upon build and therefore don't have to update webserver config on update. You find necessary information here: https://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls

**Comment by rugk** [comment]
Okay good ideas.
Personally I would be satisfied if it just writes these headers into a text file so I can manually out them into the severe config. In this case I only have to copy and paste them. :smile:
As I have to do things manually when upgrading croodle this small extra step does not matter for me.

**Comment by jelhan** [comment]
```
$ ls -1 assets/ | while read asset; do echo "Link \"assets/${asset};rel=preload\""; done
Link "assets/croodle-42165be9359b15fd6c3105d5bbcb4140.js;rel=preload"
Link "assets/croodle-4fa870d30e23f73c6360c84ffe998747.css;rel=preload"
Link "assets/vendor-b7e28f60c9d7d8f8e205dbaec70ef349.js;rel=preload"
Link "assets/vendor-d625e2497bc24a682c987bc29adcbbb4.css;rel=preload"
```

HTTP/2 push priorities seems to be a really complex topic. Haven't dig deeper into yet. So can't help here.

**Comment by rugk** [comment]
Nice idea with the shell command. I think I'll write a shell script to expand this a bit, because you alos need the "as"  part...

**Comment by rugk** [comment]
So here it finally is: https://gist.github.com/rugk/d242a539979942f98db11bf7a8ab1bde

**Comment by jelhan** [comment]
Nice. Thanks for sharing.
