### ISSUE TITLE
Missing translation on error page/unexpected error instead of 404 error

### ISSUE THREAD

**Issue by sappor0** [jelhan/croodle#214]
Steps to reproduce:

1. Go to random non-existant poll: http://localhost:4200/#/poll/xxxxxxxxxxxxxxxxxxxx
2. This produces the following errors:
  * Instead of rendering the 404 error page, this actually renders the generic 'unexpected error' page.
  * The unexpected error strings are not found in any locale:
  ```
  Missing translation: error.poll.unexpected.title
  Missing translation: error.poll.unexpected.description
  ```

**Comment by jelhan** [comment]
Seems like API throws and returns with HTTP status code `500` if poll is not found. There is a test which should cover this case: https://github.com/jelhan/croodle/blob/master/api/tests/api/GetNotExistingPollCept.php

If API returns a `500`, Frontend renders an _Unexpected error_. This is expected behavior.

**Comment by jelhan** [comment]
Actually it might be caused by an invalid poll ID. Seems like API throws a `500` if poll ID is not following the constraints defined here: https://github.com/jelhan/croodle/blob/32e5971abaa6ded8f4d81c6d7b48ba4244c7c666/api/classes/poll.php#L117-L121

I wasn't able to reproduce with an ID that follows that constraints.
