### ISSUE TITLE
Yes/No/maybe icons and colors got lost with latest release

### ISSUE THREAD

**Issue by doobry-systemli** [jelhan/croodle#274]
While I really like the clean new design of croodle 0.6.0 (well done!), I miss the colors and icons of Yes/No/maybe options in polls that earlier versions had. They helped a lot do visually detect patterns in the results table.

In croodle 0.5.6:

![croodle_0 5 6](https://user-images.githubusercontent.com/25278864/67944779-8fc66980-fbdd-11e9-800d-40a0f77b5520.png)

In croodle 0.6.0-rc.1:

![croodle_0 6 0-rc 1](https://user-images.githubusercontent.com/25278864/67944742-74f3f500-fbdd-11e9-8618-e654278af647.png)

**Comment by jelhan** [comment]
@sappor0 I think the styles were removed in #205. Was this change intended?

**Comment by sappor0** [comment]
The change was intentional to reduce visual clutter. I agree that the removed colour coding is less clear though. Moving forward I think the idea was that the whole results screen should get a revamp that's why I didn't spend more time on this.

As a interim step I propose something like this:

![Screenshot from 2019-11-01 14-51-18](https://user-images.githubusercontent.com/51237191/68029259-287ce800-fcb7-11e9-99e3-5c55a9ccccaa.png)

**Comment by doobry-systemli** [comment]
I very much like @sappor0's proposal! :+1:

**Comment by jelhan** [comment]
@sappor0 Thanks a lot for your quick feedback. The proposed interim solution looks great. Do you have time to implement that one yourself?

**Comment by sappor0** [comment]
@jelhan Sorry for the late reply. I will try to put together a MR within the next week.

**Comment by sappor0** [comment]
Ah. Just saw your MR. Awesome!

**Comment by sappor0** [comment]
@jelhan Incidentally I've put the thumb screws on the designer who said they would make a wireframe for the results screen. So hopefully we should have something to discuss in the near future.
