### ISSUE TITLE
Icon used for save button is confusing

### ISSUE THREAD

**Issue by jelhan** [jelhan/croodle#294]
Croodle uses the same icon for *next* as for *save* button. While it's a good fit for *next* button it does not make much sense for *save* button.

![save-button](https://user-images.githubusercontent.com/4965703/68548288-87dfa400-03eb-11ea-9f81-5085c8ba8edf.png)
![next-button](https://user-images.githubusercontent.com/4965703/68548290-8ada9480-03eb-11ea-9fd9-dfe1a5f10985.png)

The icon for the save button should be changed.

This save button is used at two places: at last step of poll creation form and for participation.

I guess there is a technical issue for this situation: both buttons use the same component, which is called `<NextButton>`. It could be used in block mode to overrule default text. I think it's time for a new component `<SaveButton>` rather than adding more functionality to `<NextButton>` to alter the icon.

**Comment by jelhan** [comment]
@sappor0 I'm not that used to Open Iconic. Is there an icon you could recommend for a save button? Tried to filter there icons by *save* but that returned nothing.

**Comment by sappor0** [comment]
… So we're not the first people to have this issue at least https://github.com/iconic/open-iconic/issues/41

There is some debate about the validity of the save icon with the diskette as it is obsolete skeumorphism and most young people don't know what it represents. (https://graphicdesign.stackexchange.com/questions/323/new-generation-of-save-icon-that-is-not-a-disk) – The counter-argument to a new save icon is that an icon needs to be simply iconic and ubiquitous and not realistic.

Me, I'm somewhere in the middle. I think we can use something a little different and it would still work. (especially since we're combining it with a label)

I think there are a few likely candidates we can use (in order of my personal preference):

* ![Screenshot from 2019-11-12 12-15-08](https://user-images.githubusercontent.com/51237191/68667657-d05fa480-0546-11ea-821a-7534b6e5f4d5.png)

* ![Screenshot from 2019-11-12 12-15-17](https://user-images.githubusercontent.com/51237191/68667658-d0f83b00-0546-11ea-9ee4-6254f99c9b02.png)

* ![Screenshot from 2019-11-12 12-15-27](https://user-images.githubusercontent.com/51237191/68667659-d0f83b00-0546-11ea-9e98-db2e506bb31e.png)

* ![Screenshot from 2019-11-12 12-15-50](https://user-images.githubusercontent.com/51237191/68667660-d0f83b00-0546-11ea-8f0d-4fb7d174385b.png)

**Comment by extralooping** [comment]
i'd vote for the checkmark icon. ich think the important meaning here that it is final step which completes the action

**Comment by jelhan** [comment]
I tend toward the cloud upload (even so it's not a file upload) or the document one. But I don't have a strong opinion here.

> i'd vote for the checkmark icon. ich think the important meaning here is that it is final step which completes the action

This argument only applies for the save button on poll creation and for the one to save a participation, isn't it? Would you use a different icon on the button to save a participation?

**Comment by extralooping** [comment]
> This argument only applies for the save button on poll creation and for the one to save a participation, isn't it? Would you use a different icon on the button to save a participation?

Your are confirming your entries. So i think, it still makes sense in this case.

**Comment by jelhan** [comment]
Three persons, three opinions. :laughing: But I noticed that I hadn't given any arguments. So let me quickly give some:

- I think the cloud upload icon stands for sending data to the cloud. The cloud represents for many people these days where the place where data is living. Maybe similar as the floppy disk of the "traditional" save icon.
- The document icon reminds me of icons used in other applications to create a document. It does not rely represent the persistence aspect of the save action though.

@sappor0 Thanks a lot for putting the options together with context. Would you feel comfortable with making a decision?

**Comment by sappor0** [comment]
Hm. Well I'm split 50/50 between cloud icon and checkmark.

* The cloud icon is more informative (I agree with what you say it represents for most people @jelhan ) which is good because we want to inform the users about what consequences their actions have.
* The checkmark is more generic/universal and probably more meaningful for non-techie users. We could reuse it in situations where no actual HTTP request will be performed but which still confirms something.

… So even though I'm still quite torn I think it should be the checkmark because it is the most accessible solution.

**Comment by jelhan** [comment]
@sappor0 sounds good. Thanks a lot for driving this discussion. Do you have time to provide a PR?
