### ISSUE TITLE
cannot use absolute dataDir

### ISSUE THREAD

**Issue by agolks** [jelhan/croodle#362]
the README states, that one should move the dataDir outside the www folder, relative or absolute. yet absolute paths are not working with cron.php.
i have set dataDir to /srv/croodle/data, but cron.php does put the cwd in front:

PHP Warning:  opendir(/var/www/croodle/api//srv/croodle/data/): failed to open dir: No such file or directory in /var/www/croodle/api/cron.php on line 23
PHP Fatal error:  Uncaught exception 'Exception' with message 'could not open data dir' in /var/www/croodle/api/cron.php:25
Stack trace:
#0 {main}
  thrown in /var/www/croodle/api/cron.php on line 25

removing $path from "$path . $config['dataDir'])" in cron.php fixes my use case, but my php knowledge is not good enough for better fix like catching relative paths, etc.

**Comment by jelhan** [comment]
@agolks Thanks a lot for reporting. I think your finding was correct.

`$path` is the absolute path to the folder `api/` subfolder of deployed code. If `dataDir` is a relative path, this folder the base directory. If `dataDir` is an absolute URL it must not be prefixed with that base directory.

This should be fixed in #363. Could you please test if it works for you? To avoid rebuilding the full project, you could replace `api/cron.php` in the latest build with the file of that feature branch.

**Comment by jelhan** [comment]
Done a little bit more testing on #363 and think it should solve the bug. Released as part of `v0.6.2`. Let me know if you still face the bug after upgrade.

**Comment by agolks** [comment]
sorry for the late response!
your fix works, thanks!
