### ISSUE TITLE
Provide "latest" tag for latest release

### ISSUE THREAD

**Issue by t2d** [jelhan/croodle#73]
This would ease the deployment.
Described here: https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release

**Comment by t2d** [comment]
Probably, Github produces this tag itself. And it is not available because of pre-release.
Anyway, would be nice for the future.

**Comment by jelhan** [comment]
You are right. `/release/latest` redirect did not consider pre-releases and since there wasn't any releases it has pointed to nothing. Following semver specification a major version zero is not considered a pre-release. So removed pre-release flag on them. You could now use `https://github.com/jelhan/croodle/releases/latest`.
